export const QUERY_KEYS = {
  GET_TASK: "GET_TASK",
  POST_TASK: "POST_TASK",
  PATCH_TASK: "PATCH_TASK",
  DELETE_TASK: "DELETE_TASK",

  GET_TASK_MEMBER: "GET_TASK_MEMBER",
  POST_TASK_MEMBER: "POST_TASK_MEMBER",
  DELETE_TASK_MEMBER: "DELETE_TASK_MEMBER",

  GET_MEETINGS: "GET_MEETINGS",
  POST_MEETING: "POST_MEETING",
  PATCH_MEETING: "PATCH_MEETING",
  DELETE_MEETING: "DELETE_MEETING",

  GET_MEETING_STAFF: "GET_MEETING_STAFF",
  POST_MEETING_STAFF: "POST_MEETING_STAFF",
  DELETE_MEETING_STAFF: "DELETE_MEETING_STAFF",

  GET_MEETING_CLIENT: "GET_MEETING_CLIENT",
  POST_MEETING_CLIENT: "POST_MEETING_CLIENT",
  DELETE_MEETING_CLIENT: "DELETE_MEETING_CLIENT",

  GET_TASK_TYPES: "GET_TASK_TYPES",
  PATCH_TASK_TYPES: "PATCH_TASK_TYPES",
  POST_TASK_TYPES: "POST_TASK_TYPES",

  GET_CLIENTS: "GET_CLIENTS",
  GET_CLIENT_DETAILS: "GET_CLIENT_DETAILS",
  POST_CLIENT: "POST_CLIENT",
  PATCH_CLIENT: "PATCH_CLIENT",
  DELETE_CLIENT: "DELETE_CLIENT",

  GET_STAFF: "GET_STAFF",
  GET_STAFF_DETAILS: "GET_STAFF_DETAILS",
  POST_STAFF: "POST_STAFF",
  PATCH_STAFF: "PATCH_STAFF",
  DELETE_STAFF: "DELETE_STAFF",

  GET_ROLES: "GET_ROLES",
  POST_ROLE: "POST_ROLE",

  GET_CUSTOMERS: "GET_CUSTOMERS",
  GET_CUSTOMER_DETAILS: "GET_CUSTOMER_DETAILS",
  POST_CUSTOMER: "POST_CUSTOMER",
  PATCH_CUSTOMER: "PATCH_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",

  GET_OFFICE_HOURS: "GET_OFFICE_HOURS",
  POST_OFFICE_HOURS: "POST_OFFICE_HOURS",
  DELETE_OFFICE_HOURS: "DELETE_OFFICE_HOURS",
};
